# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R

sudo: required

cache: packages

r:
  - devel

os:
  - linux
  - osx

apt_packages:
  - libcurl4-openssl-dev

r_packages:
  - covr
  - devtools
  - knitr
  - roxygen2
  - rmarkdown
  - testthat
  - futile.logger
  - configr
  - git2r
  - R.utils
  - RCurl
  - rvest
  - prettydoc
  - DT

r_github_packages:
  - ropensci/git2r

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library("covr"); covr::codecov()'
