# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R

sudo: required

cache: packages

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

r:
  - devel

os:
  - linux

apt_packages:
  - libcurl4-openssl-dev

r_packages:
  - covr
  - RcppTOML
  - devtools
  - knitr
  - roxygen2
  - rmarkdown
  - testthat
  - futile.logger
  - configr
  - git2r
  - R.utils
  - RCurl
  - rvest
  - prettydoc
  - DT
  - shiny
  - liteq

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library("covr"); covr::codecov()'
