title = "BioInstaller databases main repo."

[db_oncotator]
source_url = "ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/oncotator/oncotator_{{version}}.tar.gz"
version_available = ["v1_ds_April052016"]

[db_srnanalyzer]
source_url = "http://srnanalyzer.systemsbiology.net/downloads/{{version}}.tar.gz"
version_available = ["sRNA_DBs", "MainDBs", "NCBI_NonHuman"]
version_description = ["small RNA Databases", "Human and Exogenous Databases", "NCBI Non-Human Databases"]

[db_cscd]
source_url="http://gb.whu.edu.cn/CSCD/public/static/download/{{version}}.tar.gz"

version_available = ["hg19-cancer-circrna", "hg19-cancer-circrna-mre", "hg19-cancer-circrna-rbp", "hg19-cancer-circrna-orf", "hg19-normal-circrna", "hg19-normal-circrna-mre", "hg19-normal-circrna-rbp", "hg19-normal-circrna-orf", "hg19-common-circrna", "hg19-common-circrna-mre", "hg19-common-circrna-rbp", "hg19-common-circrna-orf", "hg38-cancer-circrna", "hg38-cancer-circrna-mre", "hg38-cancer-circrna-rbp", "hg38-cancer-circrna-orf", "hg38-normal-circrna", "hg38-normal-circrna-mre", "hg38-normal-circrna-rbp", "hg38-normal-circrna-orf", "hg38-common-circrna", "hg38-common-circrna-mre", "hg38-common-circrna-rbp", "hg38-common-circrna-orf"]

[db_differentialnet]
source_url = "http://netbio.bgu.ac.il/diffnet-interactomes/@>@str_replace('{{version}}', '_.*', '')@<@/@>@str_replace('{{version}}', '.*_', '')@<@.tsv"
decompress = false
version_available = ["HPA_Adrenal", "HPA_Appendix", "HPA_Bonemarrow", "HPA_Brain", "HPA_Colon", "HPA_Endometrium", "HPA_Esophagus", "HPA_FallopianTube", "HPA_Fat", "HPA_Gallbladder", "HPA_Heart", "HPA_Kidney", "HPA_Liver", "HPA_Lung", "HPA_LymphNode", "HPA_Ovary", "HPA_Placenta", "HPA_Prostate", "HPA_Rectum", "HPA_SalivaryGland", "HPA_SkeletalMuscle", "HPA_Skin", "HPA_SmallIntestine", "HPA_SmoothMuscle", "HPA_Spleen", "HPA_Stomach", "HPA_Testis", "HPA_Thyroid", "HPA_Tonsil", "GTEx_Adipose - Subcutaneous", "GTEx_Adipose - Visceral (Omentum)", "GTEx_Artery - Aorta", "GTEx_Artery - Coronary", "GTEx_Artery - Tibial", "GTEx_Brain - Amygdala", "GTEx_Brain - Anterior cingulate cortex (BA24)", "GTEx_Brain - Caudate (basal ganglia)", "GTEx_Brain - Cerebellar Hemisphere", "GTEx_Brain - Cerebellum", "GTEx_Brain - Cortex", "GTEx_Brain - Frontal Cortex (BA9)", "GTEx_Brain - Hippocampus", "GTEx_Brain - Hypothalamus", "GTEx_Brain - Nucleus accumbens (basal ganglia)", "GTEx_Brain - Putamen (basal ganglia)", "GTEx_Brain - Spinal cord (cervical c-1)", "GTEx_Brain - Substantia nigra", "GTEx_Breast - Mammary Tissue", "GTEx_Cells - EBV-transformed lymphocytes", "GTEx_Cells - Transformed fibroblasts", "GTEx_Colon - Sigmoid", "GTEx_Esophagus - Gastroesophageal Junction", "GTEx_Esophagus - Mucosa", "GTEx_Esophagus - Muscularis", "GTEx_Heart - Atrial Appendage", "GTEx_Heart - Left Ventricle", "GTEx_Liver", "GTEx_Lung", "GTEx_Minor Salivary Gland", "GTEx_Muscle - Skeletal", "GTEx_Nerve - Tibial", "GTEx_Ovary", "GTEx_Pituitary", "GTEx_Prostate", "GTEx_Skin - Not Sun Exposed (Suprapubic)", "GTEx_Skin - Sun Exposed (Lower leg)", "GTEx_Stomach", "GTEx_Testis", "GTEx_Thyroid", "GTEx_Uterus", "GTEx_Vagina", "GTEx_Whole Blood", "GTEx_Whole Brain"]

[db_seecancer]
source_url = "http://biocc.hrbmu.edu.cn/SEECancer/download/{{version}}.txt"
decompress = false
version_available = ["early_events", "late_events", "relapse_events", "metastasis_events", 
                     "drug_resistant_events", "drug_induced_events", "temporal_sequence"]

[db_diseaseenhancer]
source_url = "http://biocc.hrbmu.edu.cn/DiseaseEnhancer/RFunctions/diseaseEnh5.1.txt"
version_available = ["diseaseEnh5.1", "enhInfo", "enh2target"]

[db_pancanqtl]
source_url = "http://bioinfo.life.hust.edu.cn/PancanQTL/static/download/{{version}}.xls"
version_available = ["ACC_tumor.cis_eQTL", "BLCA_tumor.cis_eQTL", "BRCA_tumor.cis_eQTL", 
"CESC_tumor.cis_eQTL", "CHOL_tumor.cis_eQTL", "COAD_tumor.cis_eQTL", "DLBC_tumor.cis_eQTL", 
"ESCA_tumor.cis_eQTL", "GBM_tumor.cis_eQTL", "HNSC_tumor.cis_eQTL", "KICH_tumor.cis_eQTL", 
"KIRC_tumor.cis_eQTL", "KIRP_tumor.cis_eQTL", "LAML_tumor.cis_eQTL", "LGG_tumor.cis_eQTL", 
"LIHC_tumor.cis_eQTL", "LUAD_tumor.cis_eQTL", "LUSC_tumor.cis_eQTL", "MESO_tumor.cis_eQTL", 
"OV_tumor.cis_eQTL", "PAAD_tumor.cis_eQTL", "PCPG_tumor.cis_eQTL", "PRAD_tumor.cis_eQTL", 
"READ_tumor.cis_eQTL", "SARC_tumor.cis_eQTL", "SKCM_tumor.cis_eQTL", "STAD_tumor.cis_eQTL", 
"TGCT_tumor.cis_eQTL", "THCA_tumor.cis_eQTL", "THYM_tumor.cis_eQTL", "UCEC_tumor.cis_eQTL", 
"UCS_tumor.cis_eQTL", "UVM_tumor.cis_eQTL", "ACC_tumor.trans_eQTL", "BLCA_tumor.trans_eQTL", 
"BRCA_tumor.trans_eQTL", "CESC_tumor.trans_eQTL", "CHOL_tumor.trans_eQTL", "COAD_tumor.trans_eQTL", 
"DLBC_tumor.trans_eQTL", "ESCA_tumor.trans_eQTL", "GBM_tumor.trans_eQTL", "HNSC_tumor.trans_eQTL", 
"KICH_tumor.trans_eQTL", "KIRC_tumor.trans_eQTL", "KIRP_tumor.trans_eQTL", "LAML_tumor.trans_eQTL", 
"LGG_tumor.trans_eQTL", "LIHC_tumor.trans_eQTL", "LUAD_tumor.trans_eQTL", "LUSC_tumor.trans_eQTL", 
"MESO_tumor.trans_eQTL", "OV_tumor.trans_eQTL", "PAAD_tumor.trans_eQTL", "PCPG_tumor.trans_eQTL", 
"PRAD_tumor.trans_eQTL", "READ_tumor.trans_eQTL", "SARC_tumor.trans_eQTL", "SKCM_tumor.trans_eQTL", 
"STAD_tumor.trans_eQTL", "TGCT_tumor.trans_eQTL", "THCA_tumor.trans_eQTL", "THYM_tumor.trans_eQTL", 
"UCEC_tumor.trans_eQTL", "UCS_tumor.trans_eQTL", "UVM_tumor.trans_eQTL"]

[db_msdd]
source_url = "http://www.bio-bigdata.com/msdd/download/{{version}}.zip"
version_available = "msdd"

[db_mndr]
source_url = "http://www.rna-society.org/mndr/php/download.php?file={{version}}.zip"
version_available = ["All ncRNA-disease", "miRNA-disease", "lncRNA-disease"]

[db_rsnp3]
source_url = "ftp://rv.psych.ac.cn/pub/rsnp3/rSNP_info_{{version}}.tar.gz"
version_available = "all"

[db_ecodrug]
source_url = "http://bioinfo.rjh.com.cn/download/bioinstaller/ecodrug/ECOdrug_{{version}}.csv.gz"
version_available = ["eggnog", "ensembl", "inparanoid", "majority_vote"]

[db_medreaders]
source_url = ["http://bioinfo.rjh.com.cn/download/bioinstaller/medreader/paper.TF.PWM.tar.gz", 
              "http://bioinfo.rjh.com.cn/download/bioinstaller/medreader/paper.TF.summary.xlsx.gz"]
version_available = "newst"

[db_superdrug2]
source_url = ["http://bioinfo.rjh.com.cn/download/bioinstaller/superdrug2/{{version}}.csv.zip", 
              "http://bioinfo.rjh.com.cn/download/bioinstaller/superdrug2/{{version}}.zip"]
url_all_download = false
version_available = ["all_drugs_2D_structures", "all_drugs_3D_structures", "all_drugs_chemical_structure_identifiers", "all_drugs_extlinks", "all_drugs_molecular_properties", "approved_drugs_chemical_structure_identifiers", "approved_drugs_extlinks", "approved_drugs_molecular_properties"]

[db_varcards]
source_url = "http://159.226.67.237/sun/varcards/resource/download/variant/{{version}}.variant.annotation.xls.gz"
version_available = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]

[db_civic]
source_url = "https://civic.genome.wustl.edu/downloads/nightly/nightly-{{version}}.tsv"
decompress = false
version_available = ["GeneSummaries", "VariantSummaries", "VariantGroupSummaries", "ClinicalEvidenceSummaries"]
