[spack.ui.sections]
order = ["readfiles", "outputFields"]
[spack.ui.sections.ui_basic]
readfiles = "title = 'Input', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"
outputFields = "title = 'Output of spack', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"

[spack.paramters.readfiles]
# For reading annovarR shiny APP spack tool input files  
section_type = "input"
rcmd_last = """

"""
progressbar_message = "Running spack functions."
render_id = "spack_readfiles"

#!!!!! input_ui_order required related section
input_ui_order = ["start_analysis"]

[spack.paramters.readfiles.input.start_analysis]
input_id = "start_spack_analysis"
type = "shiny::actionButton"
label = "Run"

[spack.paramters.outputFields]
section_type = "output"
rcmd_last = "cat(BioInstaller::spack('find'))"
render_type = "shiny::renderPrint"
render_id = "spack_output"
output_type = "shiny::verbatimTextOutput"
progressbar_message = "spack ouput"
