[bioinstaller.ui.sections]
order = ["readfiles", "outputFields"]
[bioinstaller.ui.sections.ui_basic]
readfiles = "title = 'Input', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"
outputFields = "title = 'Output of bioinstaller', status = 'primary', width = 12, collapsed = FALSE, collapsible = TRUE"

[bioinstaller.paramters.readfiles]
# For reading annovarR shiny APP bioinstaller tool input files  
section_type = "input"
rcmd_last = """

"""
progressbar_message = "Running BioInstaller functions."
render_id = "bioinstaller_readfiles"

#!!!!! input_ui_order required related section
input_ui_order = ["start_analysis"]

[bioinstaller.paramters.readfiles.input.start_analysis]
input_id = "start_bioinstaller_analysis"
type = "shiny::actionButton"
label = "Run"

[bioinstaller.paramters.outputFields]
section_type = "output"
rcmd_last = "BioInstaller::install.bioinfo(show.all.names = TRUE)"
render_type = "shiny::renderPrint"
render_id = "bioinstaller_output"
output_type = "shiny::verbatimTextOutput"
progressbar_message = "BioInstaller outputFields"
